### ISSUE TITLE
Always putting file into container root

### ISSUE THREAD

**Issue by willianhf** [AlexanderYW/Adonis-Drive-Azure-Storage#1]
```js
await Drive.disk('azure').putStream('2020/01/1579193751291.jpg', stream);
```
That put the file into container root instead of that folder.

I think it's because `path.basename(relativePath)`

**Comment by AlexanderYW** [comment]
@willianhf you're right, I will push an update that fixes it ASAP.

**Comment by AlexanderYW** [comment]
@willianhf Check out the latest version of the package, and let me know if your issue have been fixed
