### ISSUE TITLE
getUrl returns unescaped slashes (%2F) for relative paths containing folders

### ISSUE THREAD

**Issue by baybal** [AlexanderYW/Adonis-Drive-Azure-Storage#21]
**Describe the bug**
getUrl returns unescaped slashes (%2F) for relative paths containing folders

**To Reproduce**
      const relUrl = `${folder_uuid}/${filename}`
      await storiesDisk.putStream(relUrl, readStream)
      console.log(await storiesDisk.getUrl(relUrl)
)
**Expected behavior**
URL should be unescaped

**Screenshots**
![image](https://user-images.githubusercontent.com/3344988/98518516-b069da80-2299-11eb-9174-14f0a54c0aec.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Linux

**Comment by AlexanderYW** [comment]
This issue has been resolved in 4.1.10
